version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgresdev
          POSTGRES_PASSWORD: postgresdev
          POSTGRES_DB: prayer_praise_app_test
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgresdev
      POSTGRES_PASSWORD: postgresdev
      POSTGRES_DB: prayer_praise_app_test
    steps:
      - run:
          name: Install postgres client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run: "ssh rockyj@praywithus.site 'cd /home/rockyj/app && ls -l'"
