api:
  port: 3001
  cors: true
db:
  connString: postgresql://postgresdev:postgresdev@db:5432/prayer_praise_app_dev
token:
  secret: das34rtji89sasy676768ghjttr378ikiy9ufg4dasdam4l30434kmr34r8dgfgdtj54n4334gtr5
auth0:
  url: https://rockyj.eu.auth0.com
